/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Language, TranslationSet } from './types';

export const portfolioData = {
  personal: {
    name: 'Jaswanth Kasireddi',
    email: 'jaswanth.kasireddi@gmail.com',
    phone: '+91 7995754180',
    dob: '09/01/2000',
    birthplace: {
      en: 'Narsipatnam, India',
      de: 'Narsipatnam, Indien',
    },
    currentAddress: {
      en: 'Flat 403, Annapurna Residency, Sarada nagar, 531116, Narsipatnam, India',
      de: 'Flat 403, Annapurna Residency, Sarada nagar, 531116, Narsipatnam, Indien',
    },
    gender: {
      en: 'Male',
      de: 'Männlich',
    },
    nationality: {
      en: 'Indian',
      de: 'Indisch',
    },
  },
  education: [
    {
      years: '2018 - 2023',
      eqf: 6,
      grade: '70%',
      title: {
        en: 'B.Sc. Nursing (Bachelor of Science)',
        de: 'B.sc. KRANKENPFLEGE (Bachelor of Science)',
      },
      institution: {
        en: 'Care Waltair College of Nursing | Visakhapatnam, India',
        de: 'CARE Waltair College of Nursing | Visakhapatnam, Indien',
      },
      details: {
        en: 'Advanced clinical curriculum covering medical-surgical, pediatric, obstetrics, psychiatric, and community health nursing. Highly trained in practical patient care, intravenous (IV) therapy, pharmacotherapy administration, emergency response, hospital hygiene, and precise digital clinical documentation.',
        de: 'Fortgeschrittenes klinisches Curriculum für medizinisch-chirurgische, pädiatrische, geburtshilfliche, psychiatrische und gemeindenahe Pflege. Intensiv geschult in praktischer Patientenversorgung, intravenöser (IV) Therapie, medikamentöser Behandlung, Notfallversorgung, Infektionskontrolle und präziser digitaler Pflegedokumentation.',
      },
    },
    {
      years: '2015 - 2017',
      eqf: 5,
      grade: '97.3%',
      title: {
        en: 'Board of Intermediate Education (Pre-University)',
        de: 'Oberstufenausbildung (Hochschulreife)',
      },
      institution: {
        en: 'Tirumala Junior College | Rajahmundry, India',
        de: 'Tirumala Junior College | Rajahmundry, Indien',
      },
      details: {
        en: 'Specialized in natural sciences (Biology, Botany, Zoology, Physics, and Chemistry) and English. Built exceptional analytical and critical thinking foundations with a strong focus on laboratory skills and scientific methodology.',
        de: 'Schwerpunkt auf Naturwissenschaften (Biologie, Botanik, Zoologie, Physik und Chemie) und Englisch. Hervorragende theoretische und praktische Grundlagen in wissenschaftlicher Methodik, Laborarbeit und analytischem Denken.',
      },
    },
    {
      years: '2014 - 2015',
      eqf: 4,
      grade: '8.8 CGPA',
      title: {
        en: 'Secondary School of Education (10th Standard)',
        de: 'Sekundarschulabschluss (Realschulreife)',
      },
      institution: {
        en: 'Tirumala English Medium High School | Rajahmundry, India',
        de: 'Tirumala English Medium High School | Rajahmundry, Indien',
      },
      details: {
        en: 'Core subjects: Mathematics, Physics, Chemistry, Biology, English, and Social Studies. Cultivated robust fundamental analytical, teamwork, and computing literacy skills.',
        de: 'Hauptfächer: Mathematik, Physik, Chemie, Biologie, Englisch und Gesellschaftswissenschaften. Entwicklung solider Fähigkeiten in den Bereichen logisches Denken, Teamarbeit und grundlegende Computerkompetenz.',
      },
    },
  ],
  experience: [
    {
      role: {
        en: 'Heart Failure & Emergency Care Nurse',
        de: 'Krankenpfleger - Herzinsuffizienz- und Notfallpfleger',
      },
      company: 'CARE Hospitals',
      location: {
        en: 'Visakhapatnam, India',
        de: 'Visakhapatnam, Indien',
      },
      period: '20/05/2023 - 21/03/2025',
      duration: {
        en: '2 Years',
        de: '2 Jahre',
      },
      department: {
        en: 'Emergency & Cardiology Unit',
        de: 'Notfallmedizin & Kardiologische Station',
      },
      bullets: {
        en: [
          'Provided continuous critical care and treatment monitoring to hemodynamically unstable heart failure patients.',
          'Routinely monitored patient vital signs, ECG grids, and clinical status changes, reporting deviations instantly.',
          'Administered complex physician-prescribed medications accurately (IV drips, high-alert cardiac meds, anticoagulants).',
          'Assisted doctors actively during critical procedures, emergency resuscitation, and medical crises.',
          'Educated patients and their families daily about disease management, dietary limits, and post-discharge self-care.',
          'Maintained pristine electronic health records (EHR) and professional handovers adhering to hospital guidelines.',
        ],
        de: [
          'Kontinuierliche Akut- und Intensivpflege sowie Überwachung von hämodynamisch instabilen Patienten mit Herzinsuffizienz.',
          'Routineüberwachung der Vitalparameter, des EKG-Dienstes und des klinischen Zustands bei sofortiger Reaktion auf Anomalien.',
          'Präzise Verabreichung komplexer ärztlich verordneter Medikamente (Notfallmedikation, Infusionen, Kardiaka).',
          'Aktive Assistenz der Ärzte bei Notfallinterventionen, Reanimationen und kardiologischen Akutbehandlungen.',
          'Tägliche Beratung und Patientenedukation bezüglich Krankheitsbildern, Medikation, Ernährung und Lebensstil.',
          'Lückenlose und rechtssichere digitale Pflegedokumentation sowie strukturierte Patientenschichten-Übergaben.',
        ],
      },
    },
  ],
  skills: {
    clinical: {
      en: [
        'Emergency Patient Handling',
        'Heart Failure & Cardiac Care',
        'Intravenous (IV) Therapy & Cannulation',
        'Vital Signs & ECG Interpretation',
        'Complex Pharmacotherapy Administration',
        'Infection Control & Hygiene Standards',
        'Clinical Digital Documentation',
        'Patient Education & Empathy',
      ],
      de: [
        'Notfallmedizinische Erstversorgung',
        'Herzinsuffizienz- & Kardiologische Pflege',
        'Intravenöse (IV) Therapie & Flexülen legen',
        'Vitalzeichenkontrolle & EKG-Diagnostik',
        'Komplexe Arzneimittelverabreichung',
        'Hygiene- & Infektionsschutzstandards',
        'Digitale Pflegedokumentation (EHR)',
        'Patientenaufklärung & professionelle Empathie',
      ],
    },
    soft: {
      en: [
        'Resilience under Stress',
        'Teamwork & Collaboration',
        'Attentiveness & Detail Orientation',
        'Adaptability to Diverse Cultures',
        'Willingness to Learn & Continuous Professional Development',
        'Empathetic Communication & Patient Advocacy',
      ],
      de: [
        'Stressresistenz & Krisenkompetenz',
        'Teamgeist & fächerübergreifende Kooperation',
        'Hohe Achtsamkeit & Detailgenauigkeit',
        'Interkulturelle Kompetenz',
        'Hohe Lernbereitschaft & berufsnahe Weiterbildung',
        'Einfühlsame Kommunikation & Patientenorientierung',
      ],
    },
    languages: [
      { name: 'Telugu', level: { en: 'Native (Mother Tongue)', de: 'Muttersprache' }, cefr: 'Native' },
      { name: 'English', level: { en: 'B1 CEFR (Professional Working)', de: 'B1 GER (Sehr gute Kenntnisse)' }, cefr: 'B1' },
      { name: 'German', level: { en: 'B1 CEFR (Actively Advancing to B2)', de: 'B1 GER (Kommunikationsstark, in Weiterbildung)' }, cefr: 'B1' },
    ],
  },
};

export const translations: Record<Language, TranslationSet> = {
  en: {
    nav: {
      about: 'About Me',
      education: 'Education',
      experience: 'Experience',
      skills: 'Skills',
      germanStandards: 'German Standards',
      aiTwin: 'Interviews (AI)',
      contact: 'Contact',
    },
    hero: {
      greeting: 'Guten Tag & Hello',
      badge: 'Certified Male Nurse (B.Sc. Nursing)',
      title: 'Hi, I am Jaswanth Kasireddi',
      subtitle: 'A compassionate, dual-certified Bachelor-level male nurse (Krankenpfleger) with 2 years of intensive Emergency Cardiac Experience in Visakhapatnam. Actively preparing for the Recognition Process (Anerkennungsverfahren) to join German medical centers.',
      ctaPrimary: 'Connect with Me',
      ctaSecondary: 'Chat with my AI Twin',
      trustTitle: 'Clinical Reliability & Resilience',
      trustText: 'Deep clinical education corresponding to EQF Level 6, coupled with active German certification path, ensuring high medical trust and quick onboarding in European clinics.',
    },
    about: {
      title: 'About Jaswanth',
      text1: 'My name is Jaswanth Kasireddi, born in 2000 in India. Backed by a full Bachelor of Science in Nursing, I have actively practiced in the Emergency & Cardiac sectors for two years. Nursing to me is not just a clinical job—it is a continuous pursuit of patient well-being, clinical excellence, and absolute calm under pressure.',
      text2: 'My current objective is to establish myself within the prestigious German healthcare system. I have successfully learned German up to B1 level and am actively practicing to enrich my vocabulary and grasp medical terminologies (Fachsprache) swiftly to support German clinics in providing exceptional patient care.',
      philosophyTitle: 'Nursing Philosophy',
      philosophyText: 'A patient is first a person. Compassionate listening, sharp vital monitoring, and collaborative teamwork with doctors can bridge stressful situations and optimize clinical outcomes.',
      keyFact1: 'Academic Grade',
      keyFact1Val: '70% in B.Sc. Nursing',
      keyFact2: 'Experience',
      keyFact2Val: '2 Years Emergency care',
      keyFact3: 'Language prep',
      keyFact3Val: 'German B1 Completed',
    },
    education: {
      title: 'Academic Foundations',
      subtitle: 'Rigorous medical qualification mapped to European standards.',
      eqfLabel: 'EQF (European Qualifications Framework) Level:',
      eqfLevel: 'Level',
      gradesLabel: 'Graduation Grade / Score:',
    },
    experience: {
      title: 'Professional Journey',
      subtitle: 'Two years of dedicated clinical practice in critical environments.',
      department: 'Specialty Department',
      hospital: 'Medical Facility',
    },
    skills: {
      title: 'Competence Profiles',
      subtitle: 'Validated technical specialties, interpersonal ethics, and multilingual strengths.',
      clinical: 'Clinical & Technical Specialities',
      soft: 'Interpersonal & Professional Soft Skills',
      languages: 'Language Profiles',
      motherTongue: 'Mother tongue',
      cefrLevel: 'CEFR / GER Level:',
    },
    standards: {
      title: 'German Healthcare Compatibility',
      subtitle: 'Verification values indicating full compliance with German recruitment guidelines.',
      recognitionTitle: '1. Professional Degree Recognition (Anerkennungsverfahren)',
      recognitionText: 'In Germany, a Bachelor of Science (B.Sc.) in Nursing is highly regarded and maps perfectly to the German "Pflegefachmann" profession. All modules match the critical curriculum components, indicating a smooth equivalency review via regional administrative entities (Landesprüfungsamt).',
      eqfHighlight: '2. EQF Level 6 Equivalence',
      eqfText: 'My 5-year B.Sc. Clinical Degree sits at Level 6 of the European Qualifications Framework (EQF). This represents a deep understanding of pathophysiology, pharmacology, pediatrics, and crisis care—significantly exceeding standard vocational levels.',
      languageCertTitle: '3. Language Readiness (Language B1/B2)',
      languageCertText: 'Currently holding B1 German language certificate levels (Listening, Reading, Writing, Speaking). Actively studying medical nursing vocabulary and German medical documentation standards to ensure error-free clinical records from day one.',
      statusBadge: 'Ready for German Hospitals',
    },
    aiTwin: {
      title: 'Recruite-AI Companion',
      subtitle: 'Explore my availability, clinical experiences, and migration path through my customized AI Digital Twin. Let’s save your time!',
      placeholder: 'Ask me anything (e.g., "Tell me about your emergency clinical hours", "Are you ready to migrate?")...',
      button: 'Ask Jaswanths Twin',
      welcomeMsg: "Hey there! I'm Jaswanth's AI twin. I am ready to answer anything about my 2 years of intensive cardiological CARE experience, B.Sc. nursing degree, and German language prep directly and honestly. Ask away in English or German!",
      typing: 'Jaswanth’s Twin is typing...',
      error: 'Apologies, my system is currently offline. Please review my structured CV above, or write directly to jaswanth.kasireddi@gmail.com!',
      suggest1: 'Tell me about your cardiology shifts.',
      suggest2: 'Are you open to relocating to any region in Germany?',
      suggest3: 'What is your EQF equivalence?',
    },
    contact: {
      title: 'Establish Direct Contact',
      subtitle: 'Interested in recruiting Jaswanth, or setting up a personal video interview? Let’s initiate the path.',
      getInTouch: 'Direct Credentials',
      name: 'Your Name / Institution Name',
      email: 'Official Contact Email',
      message: 'Brief Inquiry Details',
      send: 'Transmit Inquiry',
      sending: 'Transmitting secure packet...',
      success: 'Inquiry transmitted successfully! Jaswanth will respond directly via email within 24 hours.',
      hiringLabel: 'Hiring Status in Germany:',
      hiringStatus: 'Actively Interviewing / Ready for Onboarding',
    },
  },
  de: {
    nav: {
      about: 'Über mich',
      education: 'Ausbildung',
      experience: 'Berufserfahrung',
      skills: 'Kompetenzen',
      germanStandards: 'Deutsche Standards',
      aiTwin: 'KI-Interview',
      contact: 'Kontakt',
    },
    hero: {
      greeting: 'Guten Tag & Hallo',
      badge: 'Studierter Krankenpfleger (B.Sc. Nursing)',
      title: 'Ich bin Jaswanth Kasireddi',
      subtitle: 'Ein engagierter, akademisch qualifizierter Krankenpfleger mit 2 Jahren wertvoller intensivmedizinischer und kardiologischer Erfahrung bei den CARE Hospitals. Ich stehe am Anfang meines Anerkennungsverfahrens und suche Einstiegsmöglichkeiten bei deutschen Kliniken.',
      ctaPrimary: 'Kontakt aufnehmen',
      ctaSecondary: 'Mit meinem KI-Zwilling sprechen',
      trustTitle: 'Klinische Zuverlässigkeit & Resilienz',
      trustText: 'Akademische Ausbildung nach EQR-Niveau 6 (European Qualifications Framework). Mit abgeschlossenem B1-Sprachniveau und ausgeprägten Pflegekompetenzen für einen schnellen Berufseinstieg in Deutschland.',
    },
    about: {
      title: 'Wer ist Jaswanth?',
      text1: 'Mein Name ist Jaswanth Kasireddi, geboren im Jahr 2000 in Indien. Basierend auf einem fünfjährigen wissenschaftlich-praktischen Studium der Krankenpflege (B.Sc. Nursing) konnte ich zwei Jahre wertvolle Berufserfahrung im Bereich der inneren Medizin und der Notfallversorgung (Intensivabteilung) sammeln. Pflege ist für mich Passion, Verantwortung und strukturierte Ruhe.',
      text2: 'Mein klares Ziel ist es, in Deutschland als anerkannter Krankenpfleger (Pflegefachmann) tätig zu sein. Ich habe die deutsche Sprache bereits erfolgreich bis zum Niveau B1 erlernt und verfeinere meine Sprachkompetenzen täglich im Selbststudium und in Fachsprachkursen, um deutsche Krankenhäuser nahtlos und kompetent zu verstärken.',
      philosophyTitle: 'Pflegephilosophie',
      philosophyText: 'Ein Patient ist in erster Linie ein Mensch. Durch empathisches Zuhören, aufmerksame Überwachung und enger Kooperation mit dem ärztlichen Team meistern wir Stresssituationen und sichern die beste Behandlungsqualität.',
      keyFact1: 'Akademische Note',
      keyFact1Val: '70% im B.Sc. Studium',
      keyFact2: 'Berufserfahrung',
      keyFact2Val: '2 Jahre Akutpflege',
      keyFact3: 'Sprachkenntnisse',
      keyFact3Val: 'Deutsch B1 abgeschlossen',
    },
    education: {
      title: 'Akademische Qualifikation',
      subtitle: 'Fundierte wissenschaftliche Ausbildung nach europäischen EQR/EQF-Kriterien.',
      eqfLabel: 'EQR-Niveau (Europäischer Qualifikationsrahmen):',
      eqfLevel: 'Niveau',
      gradesLabel: 'Abschlussnote / Punktzahl:',
    },
    experience: {
      title: 'Berufliche Praxis',
      subtitle: 'Zwei Jahre intensive Einsätze in der kardiologischen Notfallmedizin.',
      department: 'Fachabteilung',
      hospital: 'Klinik / Arbeitsstätte',
    },
    skills: {
      title: 'Kompetenzprofile',
      subtitle: 'Validierte Fachkompetenzen, Soft Skills und Sprachniveaus auf einen Blick.',
      clinical: 'Pflegefachthemen & klinische Schwerpunkte',
      soft: 'Soziale Kompetenzen & Arbeitsphilosophie',
      languages: 'Sprachkompetenzen (CEFR)',
      motherTongue: 'Muttersprache',
      cefrLevel: 'GER-Mittelwert:',
    },
    standards: {
      title: 'Deutsche Pflegerichtlinien',
      subtitle: 'Kennzahlen für eine reibungslose Zulassung und rasche Beschäftigung im deutschen Gesundheitssystem.',
      recognitionTitle: '1. Berufliche Anerkennung (Pflegefachmann)',
      recognitionText: 'Mein akademischer Abschluss in Bachelor of Science in Nursing qualifiziert mich für die Zulassung zur Rechtsprüfung oder der direkten Gleichstellung nach dem neuen Pflegeberufegesetz (PflBG). Die Kernfächer decken alle klinischen Stunden vollumfänglich ab.',
      eqfHighlight: '2. EQR-Niveau 6 (EQF equivalence)',
      eqfText: 'Das B.Sc. Studium ist im Europäischen Qualifikationsrahmen auf Niveau 6 (äquivalent zum deutschen Bachelor / Meisterniveau) eingestuft. Dies bürgt im Vergleich zur rein betrieblichen Ausbildung für vertieftes fachliches Reflexionsvermögen und pathophysiologische Exzellenz.',
      languageCertTitle: '3. Sprachliche Integration (Deutsch B1/B2)',
      languageCertText: 'Nachweisbare B1-Kenntnisse in allen Teilbereichen (Hören, Lesen, Schreiben, Sprechen). Aktive Vorbereitung auf den Klinikalltag durch Aneignung medizinischer Fachbegriffe (Anamnese, Dokumentation), um Behandlungsfehler durch Missverständnisse auszuschließen.',
      statusBadge: 'Bereit für deutsche Kliniken',
    },
    aiTwin: {
      title: 'KI-Recruiting-Assistent',
      subtitle: 'Testen Sie meine Eignung, Absichten und Fachstunden im interaktiven Gespräch mit meinem digitalen Zwilling. Innovativ und zeitsparend.',
      placeholder: 'Fragen Sie den KI-Zwilling (z. B. „Erzähle mir von deiner Erfahrung mit kardiologischen Notfällen“ oder „Wann kannst du anfangen?“)...',
      button: 'KI-Zwilling befragen',
      welcomeMsg: 'Hallo! Ich bin Jaswanths KI-Zwilling. Frag mich einfach direkt alles über meine kardiologische Erfahrung, mein Studium oder meinen Umzug nach Deutschland. Ich antworte kurz und knackig auf Deutsch oder Englisch!',
      typing: 'KI-Zwilling schreibt...',
      error: 'Entschuldigung, meine Systemverbindung ist kurzzeitig unterbrochen. Bitte werfen Sie einen Blick auf meinen Lebenslauf oben oder senden Sie eine direkte E-Mail an jaswanth.kasireddi@gmail.com!',
      suggest1: 'Wie sieht deine Erfahrung bei Herzinsuffizienz aus?',
      suggest2: 'Bist du flexibel bei der Standortwahl in Deutschland?',
      suggest3: 'Was zeichnet deine Teamarbeit aus?',
    },
    contact: {
      title: 'Direkt kontaktieren',
      subtitle: 'Möchten Sie ein persönliches Erstgespräch per Video (Teams/Zoom) führen oder meine Zeugnismappe anfordern?',
      getInTouch: 'Kontaktdaten',
      name: 'Ihr Name / Name der Einrichtung',
      email: 'Offizielle Kontaktadresse',
      message: 'Details der Anfrage',
      send: 'Anfrage absenden',
      sending: 'Sichere Übertragung gestartet...',
      success: 'Anfrage erfolgreich übertragen! Jaswanth wird sich innerhalb von 12 bis 24 Stunden persönlich bei Ihnen melden.',
      hiringLabel: 'Arbeitsstatus für Deutschland:',
      hiringStatus: 'Suchend / Bereit für Anerkennung & Visum',
    },
  },
};
